### ISSUE TITLE
Move to new MongoDB Drivers

### ISSUE THREAD

**Issue by GermanGeekN** [sboesebeck/morphium#61]
Move to mongodb java driver V4.x. This has some implications, but should be fine.

We should also investigate in that area, if we could switch serialization to `Map<Object,Object>` - this might be possible, if we register custom codecs with the mongodb driver. out of the box, it will not work properly.

Maybe we could also get more use of the Codes in mongodb driver when object serialization

**Comment by sboesebeck** [comment]
I agree... at least to the upgrade of the mongodb driver.

Using the codecs is a bit more complicated though. in order to do that, we need to be sure that the InMemoryDriver still works. The Codecs produce BSON-Values or similar. The InMemDriver works with Maps... 

This is probably not as easy as it sounds.

**Comment by sboesebeck** [comment]
done in develop
